application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      brandads:
        license: Apache-2.0
        actions:
          getads:
            function: actions/getads/index.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            annotations:
              final: true
          getads1:
            function: actions/getads/index.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            annotations:
              final: true

          getpages:
            function: actions/getpages/index.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
            annotations:
              final: true
